version: '3'
services:
    # app:
    #  build:
    #    context: .
    #    dockerfile: Dockerfile
    #  container_name: horeca-production 
    #  ports:
    #    - 8230:80

    httpd:
        image: httpd:latest
        container_name: httpd-app-easy
        volumes:
 
           - ./dist:/usr/local/apache2/htdocs/
 
        ports:
         - 8232:80
        # depends_on:
        #  - app
