version: '3'
services:
    # app:
    #  build:
    #    context: .
    #    dockerfile: Dockerfile
    #  container_name: horeca-production 
    #  ports:
    #    - 8230:80

    nginx:
        image: nginx:alpine
        container_name: nginx-app
        volumes:
           -  ./conf/nginx.conf:/etc/nginx/nginx.conf
           - ./dist:/usr/share/nginx/html
 
        ports:
         - 8232:80
        # depends_on:
        #  - app
